version: "3.8"
services:
  app:
    build: ./app
    ports: 
      - 5000:5000
    environment: 
      DB_URL: bla
    depends_on: 
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: exercise_two
      POSTGRES_USER: exercise2user
      POSTGRES_PASSWORD: exercise2
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
