version: "3.8"
services:
  app:
    build: ./app
    ports: 
      - 5000:5000
    environment:
      DB_HOST: db
      DB_PORT: 5432 
      DB_NAME: exercise_two
      DB_USER: exercise2user
      DB_PASS: exercise2
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: exercise_two
      POSTGRES_USER: exercise2user
      POSTGRES_PASSWORD: exercise2
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d exercise_two -U exercise2user"]
      interval: 10s
      timeout: 5s
      retries: 5
